"""empty message

Revision ID: 103291394e89
Revises: a13e82eb5622
Create Date: 2021-08-19 22:24:33.598136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "103291394e89"
down_revision = "a13e82eb5622"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction_type",
        sa.Column(
            "type", sa.Enum("buy", "sell", name="transaction_type"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction_type", "type")
    # ### end Alembic commands ###
