"""empty message

Revision ID: 196742b88c5f
Revises: f4b76e18c82f
Create Date: 2021-08-20 12:26:59.401516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196742b88c5f'
down_revision = 'f4b76e18c82f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('BUY', 'SELL', name='transactiontypespostgresenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_type')
    # ### end Alembic commands ###
