"""empty message

Revision ID: 3756e01fd53d
Revises: e4ee93dc235f
Create Date: 2021-09-19 13:31:28.350735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3756e01fd53d'
down_revision = 'e4ee93dc235f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('shares', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'shares')
    # ### end Alembic commands ###
