"""empty message

Revision ID: 5939083ceb12
Revises: bc65dc1211bf
Create Date: 2021-08-26 00:05:24.593971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5939083ceb12'
down_revision = 'bc65dc1211bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('BUY', 'SELL', name='transactiontypespostgresenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transaction_types')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_types',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('buy', 'sell', name='transactiontypes'), autoincrement=False, nullable=True)
    )
    op.drop_table('transaction_type')
    # ### end Alembic commands ###
