"""empty message

Revision ID: 76dec1471fab
Revises: 8548e6c3ce51
Create Date: 2021-08-19 22:12:28.146301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "76dec1471fab"
down_revision = "8548e6c3ce51"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ownership",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("stock_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stock.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("transaction", sa.Column("amount", sa.Integer(), nullable=False))
    op.drop_column("transaction_type", "name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction_type",
        sa.Column("name", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    )
    op.drop_column("transaction", "amount")
    op.drop_table("ownership")
    # ### end Alembic commands ###
