"""empty message

Revision ID: 8548e6c3ce51
Revises: a8786113dc61
Create Date: 2021-08-18 15:12:09.161932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8548e6c3ce51"
down_revision = "a8786113dc61"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("balance", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("account", "balance")
    # ### end Alembic commands ###
