"""empty message

Revision ID: 85c1ef3e2750
Revises: 196742b88c5f
Create Date: 2021-08-25 23:48:44.105897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85c1ef3e2750'
down_revision = '196742b88c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('BUY', 'SELL', name='transactiontypespostgresenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transaction_types')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_types',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('buy', 'sell', name='transactiontypes'), autoincrement=False, nullable=True)
    )
    op.drop_table('transaction_type')
    # ### end Alembic commands ###
