"""empty message

Revision ID: 997e8042c2f0
Revises: f357197f6460
Create Date: 2021-09-15 12:36:44.000457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997e8042c2f0'
down_revision = 'f357197f6460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('volatility', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'volatility')
    # ### end Alembic commands ###
