"""empty message

Revision ID: a13e82eb5622
Revises: aa4598d0e28d
Create Date: 2021-08-19 22:23:32.587432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a13e82eb5622"
down_revision = "aa4598d0e28d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction_type",
        sa.Column(
            "transaction_type",
            sa.Enum("buy", "sell", name="transaction_type"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction_type", "transaction_type")
    # ### end Alembic commands ###
