"""empty message

Revision ID: aa4598d0e28d
Revises: 76dec1471fab
Create Date: 2021-08-19 22:19:34.658178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4598d0e28d'
down_revision = '76dec1471fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_type', sa.Column('transaction_type', sa.Enum('buy', 'sell, name="transaction_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_type', 'transaction_type')
    # ### end Alembic commands ###
