"""empty message

Revision ID: abae7bc26069
Revises: b6032e0a017e
Create Date: 2021-08-20 11:59:21.367152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abae7bc26069'
down_revision = 'b6032e0a017e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    transaction_type_postgres = postgresql.ENUM('buy', 'sell', 
name='transactiontypes', create_type='FALSE')
    op.create_table('transaction_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', transaction_type_postgres), nullable=False),
    sa.PrimaryKeyConstraint('id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_type')
    # ### end Alembic commands ###
