"""empty message

Revision ID: b2c5a2ae6722
Revises: 40344331d646
Create Date: 2021-08-26 11:38:50.685236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2c5a2ae6722'
down_revision = '40344331d646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('BUY', 'SELL', name='transactiontypespostgresenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transaction_types')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_types',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('buy', 'sell', name='transactiontypes'), autoincrement=False, nullable=True)
    )
    op.drop_table('transaction_type')
    # ### end Alembic commands ###
