"""empty message

Revision ID: b662eadab8cd
Revises: a170f14a70e8
Create Date: 2021-09-29 14:56:10.561214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b662eadab8cd"
down_revision = "a170f14a70e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("test_field", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("account", "test_field")
    # ### end Alembic commands ###
