"""empty message

Revision ID: cbc28f6f0a1a
Revises: b097c273802b
Create Date: 2021-08-20 00:15:54.717160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cbc28f6f0a1a"
down_revision = "b097c273802b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type", sa.Enum("buy", "sell", name="transaction_types"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction_type")
    # ### end Alembic commands ###
