"""empty message

Revision ID: e4ee93dc235f
Revises: 772424597895
Create Date: 2021-09-19 13:17:27.329303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ee93dc235f'
down_revision = '772424597895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('transaction_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transaction', 'transaction_type', ['transaction_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'transaction_type_id')
    # ### end Alembic commands ###
