"""empty message

Revision ID: f357197f6460
Revises: 9ce70b92a7d1
Create Date: 2021-09-10 22:22:28.216785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f357197f6460'
down_revision = '9ce70b92a7d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'cash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('cash', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
